name: Build Haveno Installers

on:
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y rpm

      - name: Build Haveno Installer for Linux
        run: |
          ./gradlew clean build --refresh-keys --refresh-dependencies
          ./gradlew packageInstallers
        working-directory: .

      - name: Move Release Files
        run: |
          mkdir ${{ github.workspace }}/release
          mv desktop/build/temp-*/binaries/haveno-*.rpm ${{ github.workspace }}/release
          mv desktop/build/temp-*/binaries/haveno_*.deb ${{ github.workspace }}/release
          mv desktop/build/temp-*/binaries/desktop-*.jar.SHA-256 ${{ github.workspace }}/release

      - uses: actions/upload-artifact@v2
        with:
          name: HavenoInstaller-linux
          path: ${{ github.workspace }}/release


  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build Haveno Installer for macOS
        run: |
          ./gradlew clean build --refresh-keys --refresh-dependencies
          ./gradlew packageInstallers
        working-directory: .

      - name: Move Release Files
        run: |
          mkdir ${{ github.workspace }}/release
          mv desktop/build/temp-*/binaries/Haveno-*.dmg ${{ github.workspace }}/release
          mv desktop/build/temp-*/binaries/desktop-*.jar.SHA-256 ${{ github.workspace }}/release

      - uses: actions/upload-artifact@v2
        with:
          name: HavenoInstaller-macos
          path: ${{ github.workspace }}/release

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Install WiX Toolset
        run: |
          Invoke-WebRequest -Uri 'https://github.com/wixtoolset/wix3/releases/download/wix314rtm/wix314.exe' -OutFile wix314.exe
          .\wix314.exe /quiet /norestart
        shell: powershell

      - name: Build Haveno Installer for Windows
        run: |
          ./gradlew clean build --refresh-keys --refresh-dependencies
          ./gradlew packageInstallers
        working-directory: .

      - name: Move Release Files
        run: |
          mkdir ${{ github.workspace }}/release
          $source = Get-ChildItem -Path "${{ github.workspace }}\desktop\build" -Recurse -File
          $destination = "${{ github.workspace }}\release"
          Move-Item -Path $source -Destination $destination
        shell: powershell
        
      - uses: actions/upload-artifact@v2
        with:
          name: HavenoInstaller-windows
          path: ${{ github.workspace }}/release
